/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDealsRouteImport } from './routes/_authenticated/deals'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as OauthGoogleCalendarCallbackRouteImport } from './routes/oauth/google-calendar/callback'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings/integrations'
import { Route as AuthenticatedSettingsIntegrationsIndexRouteImport } from './routes/_authenticated/settings/integrations/index'
import { Route as AuthenticatedSettingsIntegrationsGoogleCalendarRouteImport } from './routes/_authenticated/settings/integrations/google-calendar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDealsRoute = AuthenticatedDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const OauthGoogleCalendarCallbackRoute =
  OauthGoogleCalendarCallbackRouteImport.update({
    id: '/oauth/google-calendar/callback',
    path: '/oauth/google-calendar/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsIntegrationsIndexRoute =
  AuthenticatedSettingsIntegrationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsIntegrationsRoute,
  } as any)
const AuthenticatedSettingsIntegrationsGoogleCalendarRoute =
  AuthenticatedSettingsIntegrationsGoogleCalendarRouteImport.update({
    id: '/google-calendar',
    path: '/google-calendar',
    getParentRoute: () => AuthenticatedSettingsIntegrationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/deals': typeof AuthenticatedDealsRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRouteWithChildren
  '/oauth/google-calendar/callback': typeof OauthGoogleCalendarCallbackRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/settings/integrations/google-calendar': typeof AuthenticatedSettingsIntegrationsGoogleCalendarRoute
  '/settings/integrations/': typeof AuthenticatedSettingsIntegrationsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/deals': typeof AuthenticatedDealsRoute
  '/': typeof AuthenticatedIndexRoute
  '/oauth/google-calendar/callback': typeof OauthGoogleCalendarCallbackRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/integrations/google-calendar': typeof AuthenticatedSettingsIntegrationsGoogleCalendarRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/deals': typeof AuthenticatedDealsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRouteWithChildren
  '/oauth/google-calendar/callback': typeof OauthGoogleCalendarCallbackRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/settings/integrations/google-calendar': typeof AuthenticatedSettingsIntegrationsGoogleCalendarRoute
  '/_authenticated/settings/integrations/': typeof AuthenticatedSettingsIntegrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/companies'
    | '/contacts'
    | '/deals'
    | '/settings'
    | '/settings/integrations'
    | '/oauth/google-calendar/callback'
    | '/settings/'
    | '/settings/integrations/google-calendar'
    | '/settings/integrations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/companies'
    | '/contacts'
    | '/deals'
    | '/'
    | '/oauth/google-calendar/callback'
    | '/settings'
    | '/settings/integrations/google-calendar'
    | '/settings/integrations'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/companies'
    | '/_authenticated/contacts'
    | '/_authenticated/deals'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/settings/integrations'
    | '/oauth/google-calendar/callback'
    | '/_authenticated/settings/'
    | '/_authenticated/settings/integrations/google-calendar'
    | '/_authenticated/settings/integrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OauthGoogleCalendarCallbackRoute: typeof OauthGoogleCalendarCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deals': {
      id: '/_authenticated/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AuthenticatedDealsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/oauth/google-calendar/callback': {
      id: '/oauth/google-calendar/callback'
      path: '/oauth/google-calendar/callback'
      fullPath: '/oauth/google-calendar/callback'
      preLoaderRoute: typeof OauthGoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/integrations/': {
      id: '/_authenticated/settings/integrations/'
      path: '/'
      fullPath: '/settings/integrations/'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsIntegrationsRoute
    }
    '/_authenticated/settings/integrations/google-calendar': {
      id: '/_authenticated/settings/integrations/google-calendar'
      path: '/google-calendar'
      fullPath: '/settings/integrations/google-calendar'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsGoogleCalendarRouteImport
      parentRoute: typeof AuthenticatedSettingsIntegrationsRoute
    }
  }
}

interface AuthenticatedSettingsIntegrationsRouteChildren {
  AuthenticatedSettingsIntegrationsGoogleCalendarRoute: typeof AuthenticatedSettingsIntegrationsGoogleCalendarRoute
  AuthenticatedSettingsIntegrationsIndexRoute: typeof AuthenticatedSettingsIntegrationsIndexRoute
}

const AuthenticatedSettingsIntegrationsRouteChildren: AuthenticatedSettingsIntegrationsRouteChildren =
  {
    AuthenticatedSettingsIntegrationsGoogleCalendarRoute:
      AuthenticatedSettingsIntegrationsGoogleCalendarRoute,
    AuthenticatedSettingsIntegrationsIndexRoute:
      AuthenticatedSettingsIntegrationsIndexRoute,
  }

const AuthenticatedSettingsIntegrationsRouteWithChildren =
  AuthenticatedSettingsIntegrationsRoute._addFileChildren(
    AuthenticatedSettingsIntegrationsRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRouteWithChildren
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRouteWithChildren,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDealsRoute: typeof AuthenticatedDealsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDealsRoute: AuthenticatedDealsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OauthGoogleCalendarCallbackRoute: OauthGoogleCalendarCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
